language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.0
  - android-28
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
before_script:
- echo yes | android update sdk --no-ui --all --filter platform-tools,tools
- echo yes | android update sdk --no-ui --all --filter build-tools-28.0.0
- echo yes | android update sdk --no-ui --all --filter android-28
script:
- "./gradlew clean test"
notifications:
  email:
    recipients:
      - support@madapps.in
    on_success: never
    on_failure: always

  slack: madappstechnologies:0T1TW6lCma5wp1IPYn4hRp5H